name: traefik

services:
  traefik:
    image: traefik:latest
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.traefik.address=:8080"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cert-resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.cert-resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.cert-resolver.acme.email=test@yopmail.com"
      - "--certificatesresolvers.cert-resolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certificates/letsencrypt:/letsencrypt"
    networks:
      - traefik
      
  network:
    traefik:
      name: traefik